version: "3.8"
services:
  auth-service:
    image: hobingantuk/auth-services:v1
    ports:
      - "8081:8080"
    environment:
      - MongoDbSettings__ConnectionString=${MONGO_CONNECTION_STRING}
      - MongoDbSettings__DatabaseName=${MONGO_DATABASE_NAME}
      - JwtSettings__SecretKey=${JWT_SECRET}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - JwtSettings__AccessTokenExpiryMinutes=10 # Optional, default value
      - JwtSettings__RefreshTokenExpiryDays=7  
