name: CI Workflow

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
    
jobs:
  build:
    runs-on: self-hosted

    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v3
      
      # Step 2: Set up .NET SDK
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # Replace with your .NET version

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ./AuthServices.sln

      # Step 4: Build the application
      - name: Build the application
        run: dotnet build --no-restore --configuration Release ./AuthServices.sln

      # Step 5: Run tests
      - name: Run tests
        run: dotnet test --no-restore --verbosity normal ./AuthServices.sln
